runtime: custom
env: flex

# Configuration pour Google Cloud Run
service: portfolio-bts

# Ressources allouées
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Configuration réseau
network:
  forwarded_ports:
    - 80:8080

# Variables d'environnement
env_variables:
  NGINX_PORT: 8080

# Paramètres d'autoscaling
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
